### ISSUE TITLE
Maximum recursion on import

### ISSUE THREAD

**Issue by RankoR** [Eric-Canas/qrdet#12]
I'm trying to run your sample code with Python 3.12 on Linux:

```
import cv2
from qrdet import QRDetector


def main():
    detector = QRDetector(model_size='s')
    image = cv2.imread(filename='/tmp/image.jpg')
    detections = detector.detect(image=image, is_bgr=True)

    # Draw the detections
    for detection in detections:
        x1, y1, x2, y2 = detection['bbox_xyxy']
        confidence = detection['confidence']
        segmenation_xy = detection['quadrilateral_xy']
        cv2.rectangle(image, (x1, y1), (x2, y2), color=(0, 255, 0), thickness=2)
        cv2.putText(image, f'{confidence:.2f}', (x1, y1 - 10), fontFace=cv2.FONT_HERSHEY_SIMPLEX,
                    fontScale=1, color=(0, 255, 0), thickness=2)
    # Save the results
    cv2.imwrite(filename='/tmp/image2.jpg', img=image)


if __name__ == '__main__':
    main()
```

And getting this error:

```
Traceback (most recent call last):
  File "/home/user/src/shelves-controller/demo/qrdet_demo.py", line 2, in <module>
    from qrdet import QRDetector
  File "/home/user/.venv/shelves-controller/lib/python3.12/site-packages/qrdet/__init__.py", line 4, in <module>
    from ._qrdet_helpers import crop_qr, _yolo_v8_results_to_dict, _prepare_input, _plot_result
  File "/home/user/.venv/shelves-controller/lib/python3.12/site-packages/qrdet/_qrdet_helpers.py", line 3, in <module>
    from ultralytics.engine.results import Results
  File "/home/user/.venv/shelves-controller/lib/python3.12/site-packages/ultralytics/__init__.py", line 10, in <module>
    from ultralytics.data.explorer.explorer import Explorer
  File "/home/user/.venv/shelves-controller/lib/python3.12/site-packages/ultralytics/data/explorer/explorer.py", line 17, in <module>
    from ultralytics.models.yolo.model import YOLO
  File "/home/user/.venv/shelves-controller/lib/python3.12/site-packages/ultralytics/models/__init__.py", line 6, in <module>
    from .sam import SAM
  File "/home/user/.venv/shelves-controller/lib/python3.12/site-packages/ultralytics/models/sam/__init__.py", line 3, in <module>
    from .model import SAM
  File "/home/user/.venv/shelves-controller/lib/python3.12/site-packages/ultralytics/models/sam/model.py", line 22, in <module>
    from .build import build_sam
  File "/home/user/.venv/shelves-controller/lib/python3.12/site-packages/ultralytics/models/sam/build.py", line 18, in <module>
    from .modules.tiny_encoder import TinyViT
  File "/home/user/.venv/shelves-controller/lib/python3.12/site-packages/ultralytics/models/sam/modules/tiny_encoder.py", line 18, in <module>
    import torch.utils.checkpoint as checkpoint
  File "/home/user/.venv/shelves-controller/lib/python3.12/site-packages/torch/utils/checkpoint.py", line 23, in <module>
    from torch._functorch._aot_autograd.functional_utils import is_fun
  File "/home/user/.venv/shelves-controller/lib/python3.12/site-packages/torch/_functorch/_aot_autograd/functional_utils.py", line 13, in <module>
    from torch.fx.experimental.symbolic_shapes import definitely_true, sym_eq
  File "/home/user/.venv/shelves-controller/lib/python3.12/site-packages/torch/fx/experimental/symbolic_shapes.py", line 63, in <module>
    from torch.utils._sympy.functions import FloorDiv, Mod, IsNonOverlappingAndDenseIndicator
  File "/home/user/.venv/shelves-controller/lib/python3.12/site-packages/torch/utils/_sympy/functions.py", line 1, in <module>
    import sympy
  File "/home/user/.venv/shelves-controller/lib/python3.12/site-packages/sympy/__init__.py", line 74, in <module>
    from .polys import (Poly, PurePoly, poly_from_expr, parallel_poly_from_expr,
  File "/home/user/.venv/shelves-controller/lib/python3.12/site-packages/sympy/polys/__init__.py", line 93, in <module>
    from .numberfields import (minpoly, minimal_polynomial, primitive_element,
  File "/home/user/.venv/shelves-controller/lib/python3.12/site-packages/sympy/polys/numberfields/__init__.py", line 27, in <module>
    from .galoisgroups import galois_group
  File "/home/user/.venv/shelves-controller/lib/python3.12/site-packages/sympy/polys/numberfields/galoisgroups.py", line 24, in <module>
    from sympy.polys.numberfields.galois_resolvents import (
  File "/home/user/.venv/shelves-controller/lib/python3.12/site-packages/sympy/polys/numberfields/galois_resolvents.py", line 28, in <module>
    from sympy.polys.numberfields.resolvent_lookup import resolvent_coeff_lambdas
RecursionError: maximum recursion depth exceeded during compilation
```

`qrdet==2.5`. Also checked with `2.4` and `2.0` with the same result.

Not sure if it happens only to me.

UPD. Looks like `sympy` issue. ultralytics installs the latest version, and I face this problem with it. But if I install `1.11.1` it's ok.

**Comment by RankoR** [comment]
Created a pull request: https://github.com/Eric-Canas/qrdet/pull/13
