### ISSUE TITLE
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 2.73 PiB for an array with shape (75120264, 13658175, 3) and data type uint8

### ISSUE THREAD

**Issue by hzane** [Eric-Canas/qrdet#5]
```
Traceback (most recent call last):
  File "/repo.d/zero-classification/aitec/qrcode-read.py", line 68, in <module>
    CLI(main)
  File "/home/hzane/.local/lib/python3.11/site-packages/jsonargparse/cli.py", line 77, in CLI
    return _run_component(component, cfg_init)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hzane/.local/lib/python3.11/site-packages/jsonargparse/cli.py", line 133, in _run_component
    return component(**cfg)
           ^^^^^^^^^^^^^^^^
  File "/repo.d/zero-classification/aitec/qrcode-read.py", line 60, in main
    texts = qread(reader, imgpath)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/repo.d/zero-classification/aitec/qrcode-read.py", line 31, in qread
    dets = reader.detect_and_decode(image = image)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hzane/miniconda3/envs/tools11/lib/python3.11/site-packages/qreader.py", line 132, in detect_and_decode
    detections = self.detect(image=image, is_bgr=is_bgr)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hzane/miniconda3/envs/tools11/lib/python3.11/site-packages/qreader.py", line 79, in detect
    return self.detector.detect(image=image, is_bgr=is_bgr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hzane/miniconda3/envs/tools11/lib/python3.11/site-packages/qrdet/qrdet.py", line 80, in detect
    results = _yolo_v8_results_to_dict(results = results[0], image=image)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hzane/miniconda3/envs/tools11/lib/python3.11/site-packages/qrdet/_qrdet_helpers.py", line 100, in _yolo_v8_results_to_dict
    crop_qr(image=image, detection=detections[0], crop_key=PADDED_QUAD_XYN)
  File "/home/hzane/miniconda3/envs/tools11/lib/python3.11/site-packages/qrdet/_qrdet_helpers.py", line 199, in crop_qr
    image = np.pad(image, ((top_pad, bottom_pad), (left_pad, right_pad), (0, 0)), mode='constant',
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hzane/miniconda3/envs/tools11/lib/python3.11/site-packages/numpy/lib/arraypad.py", line 798, in pad
    padded, original_area_slice = _pad_simple(array, pad_width)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hzane/miniconda3/envs/tools11/lib/python3.11/site-packages/numpy/lib/arraypad.py", line 114, in _pad_simple
    padded = np.empty(new_shape, dtype=array.dtype, order=order)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 2.73 PiB for an array with shape (75120264, 13658175, 3) and data type uint8
```

**Comment by Eric-Canas** [comment]
Hi! 

Sorry, yes. That's a problem with [quadrilateral-fitter](https://github.com/Eric-Canas/quadrilateral-fitter). When calculates the 4 points mask from the noisy QR mask, the segmentation model gives.

It should be solved yet. 

Please, tell me if you find that problem again and I will take another look at it
